baseURL = "https://blog.alienzj.tech/"

defaultContentLanguage = "zh-cn"

languageCode = "en-us"

title = "ZJ Blog"

theme = "DoIt"


[params]
  # DoIt 主题版本
  version = "0.4.X"

  description = "ZJ Blog"

  # 网站关键词
  keywords = ["Blog", "部落格", "博客", "alienzj", "ohmeta"]
  # 网站默认主题样式 ("light", "dark", "auto")
  defaultTheme = "auto"
  # DoIt 新增 | 0.2.11 开启 PWA 支持
  enablePWA = false

  # 页面头部导航栏配置
  [params.header]
    # 桌面端导航栏模式 ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # 移动端导航栏模式 ("fixed", "normal", "auto")
    mobileMode = "auto"
    # DoIt 新增 | 0.2.0 页面头部导航栏标题配置
    [params.header.title]
      # LOGO 的 URL（不要设置这个！）
      logo = ""
      # 标题名称
      name = "ZJ Blog"
      # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
      pre = ""
      # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      post = ""
      # DoIt 新增 | 0.2.5 是否为标题显示打字机动画
      typeit = true

  # Footer config
  # 页面底部信息配置
  [params.footer]
    enable = true
    # Custom content (HTML format is supported)
    # 自定义内容 (支持 HTML 格式)
    custom = ""

    # whether to show Hugo and theme info
    # 是否显示 Hugo 和主题信息
    hugo = true
    # DoIt 新增 | 0.2.14 托管服务信息 (支持 HTML 格式)
    hostedOn = '<a title="Github Pages" href="https://docs.github.com/en/pages/" target="_blank" rel="noopener noreffer">GitHub Pages</a>'

    # whether to show copyright info
    # 是否显示版权信息
    copyright = true
    # whether to show the author
    # 是否显示作者
    author = true
    # site creation time
    # 网站创立年份
    since = 2024
    # ICP info only in China (HTML format is supported)
    # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
    icp = ""
    # license info (HTML format is supported)
    # 许可协议信息 (支持 HTML 格式)
    license= """
      <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>
    """

  #  Section (所有文章) 页面配置
  [params.section]
    # section 页面每页显示文章数量
    paginate = 1000  # 尽量一页列出所有文章
    # DoIt 新增 | 0.2.13 最近更新文章设置
    [params.section.recentlyUpdated]
      enable = true
      rss = false
      days = 30
      maxCount = 10

  #  List (目录或标签) 页面配置
  [params.list]
    # list 页面每页显示文章数量
    paginate = 1000  # 尽量一页列出所有文章

  # 社交信息设置
  [params.social]
    GitHub = "alienzj"
    Twitter = "alienzj"
    Reddit = "alienzj"
    RSS = true # RSS 格式太简陋，切换到自定义的 ATOM 格式，此参数仅用于控制显示首页的 RSS 按钮

  # DoIt 更改 | 0.2.0 文章页面配置
  [params.page]
    # DoIt 新增 | 0.2.0 是否在主页隐藏一篇文章
    hiddenFromHomePage = false
    # DoIt 新增 | 0.2.0 是否在搜索结果中隐藏一篇文章
    hiddenFromSearch = false
    # DoIt 新增 | 0.2.0 是否使用 twemoji
    twemoji = false
    # 是否使用 lightgallery
    lightgallery = false
    # DoIt 新增 | 0.2.0 是否使用 ruby 扩展语法
    ruby = true
    # DoIt 新增 | 0.2.0 是否使用 fraction 扩展语法
    fraction = true
    # DoIt 新增 | 0.2.0 是否使用 fontawesome 扩展语法
    fontawesome = true
    # 是否在文章页面显示原始 Markdown 文档链接
    linkToMarkdown = true
    # DoIt 新增 | 0.2.13 是否在文章开头显示系列导航
    seriesNavigation = true
    # DoIt 新增 | 0.2.0 目录配置
    [params.page.toc]
      # 是否使用目录
      enable = true
      # DoIt 新增 | 0.2.9 是否保持使用文章前面的静态目录
      keepStatic = false
      # 是否使侧边目录自动折叠展开
      auto = true
    # DoIt 新增 | 0.2.0 代码配置
    [params.page.code]
      # 是否显示代码块的复制按钮
      copy = true
      # 默认展开显示的代码行数
      maxShownLines = 30
    # DoIt 更改 | 0.2.0 KaTeX 数学公式
    [params.page.math]
      enable = true
      # 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # 默认行内定界符是 $ ... $ 和 \\( ... \\)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      # KaTeX 插件 copy_tex
      copyTex = true
      # KaTeX 插件 mhchem
      mhchem = true
    # DoIt 新增 | 0.2.0 Mapbox GL JS 配置
    [params.page.mapbox]
      # Mapbox GL JS 的 access token
      accessToken = ""
      # 浅色主题的地图样式
      lightStyle = "mapbox://styles/mapbox/light-v9"
      # 深色主题的地图样式
      darkStyle = "mapbox://styles/mapbox/dark-v9"
      # 是否添加 NavigationControl
      navigation = true
      # 是否添加 GeolocateControl
      geolocate = true
      # 是否添加 ScaleControl
      scale = true
      # 是否添加 FullscreenControl
      fullscreen = true
    # DoIt 更改 | 0.2.0 文章页面的分享信息设置
    [params.page.share]
      enable = true
      Twitter = true
      Mastodon = true
      Reddit = true
      HackerNews = true
    # DoIt 更改 | 0.2.0 评论系统设置
    [params.page.comment]
      enable = true
      # Disqus 评论系统设置
      [params.page.comment.disqus]
        # DoIt 新增 | 0.1.1
        enable = false
        # Disqus 的 shortname，用来在文章中启用 Disqus 评论系统
        shortname = "alienzj"
      # DoIt 新增 | 0.2.5 Utterances 评论系统设置
      [params.page.comment.utterances]
        enable = true
        # owner/repo
        repo = "alienzj/alienzj.github.io"
        issueTerm = "pathname"
        label = ""
        lightTheme = "github-light"
        darkTheme = "github-dark"
      # {{< version 0.2.0 >}} {{< link "https://waline.js.org/en/" "Waline" >}} comment config
      #[params.page.comment.waline]
      #  enable = false
      #  serverURL = "waline-comment.blog.alienzj.github.io"
      #  # emoji = ['https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo']  # custom emoji url
      #  visitor = true
      #  dark = 'auto'
      #  defaultAvatar = 'mp'
      #  requiredMeta = ['nick','mail']
      #  wordLimit = 1500

    # Page SEO config
    # 页面 SEO 配置
    [params.page.seo]
      # image URL
      # 图片 URL
      images = []
      # Publisher info
      # 出版者信息
      [params.page.seo.publisher]
        name = "alienzj"
        logoUrl = "/avatar/myself.png"
    # DoIt 新增 | 0.2.14 相关文章推荐配置
    [params.page.related]
      enable = true
      count = 3


  # DoIt 新增 | 0.2.10 网站 SEO 配置
  [params.seo]
    # 图片 URL
    image = ""
    # 缩略图 URL
    thumbnailUrl = ""


[languages]
  [languages.zh-cn]
    weight = 1
    # language code, CN only here
    languageCode = "zh-CN"
    languageName = "Simplified Chinese"
    # whether to include Chinese/Japanese/Korean
    hasCJKLanguage = true

    [languages.zh-cn.params.home.profile]
      enable = true
      # Gravatar 邮箱，用于优先在主页显示的头像
      # gravatarEmail = "xiaoyin_c@qq.com"
      # 主页显示头像的 URL
      avatarURL = "/avatar/myself.webp"
      # DoIt 更改 | 0.2.7 主页显示的网站标题 (支持 HTML 格式)
      title = ""
      # 主页显示的网站副标题
      subtitle = "Hello Blog"
      # 是否为副标题显示打字机动画
      typeit = true
      # 是否显示社交账号
      social = true
      # DoIt 新增 | 0.2.0 免责声明 (支持 HTML 格式)
      disclaimer = ""

    [languages.zh-cn.params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 10

    # DoIt 更改 | 0.2.7 第三方库文件的 CDN 设置
    # [languages.zh-cn.params.cdn]
    #   # CDN 数据文件名称, 默认不启用
    #   # 位于 "themes/DoIt/assets/data/cdn/" 目录
    #   # 可以在你的项目下相同路径存放你自己的数据文件:
    #   # "assets/data/cdn/"
    #   data = "jsdelivr.yml"
      
    [[languages.zh-cn.menu.main]]
      identifier = "series"
      pre = ""
      post = ""
      name = "系列"
      url = "/series/"
      title = ""
      weight = 3
    [[languages.zh-cn.menu.main]]
      identifier = "tech"
      pre = ""
      post = ""
      name = "技术"
      url = "/categories/tech/"
      title = ""
      weight = 5
    [[languages.zh-cn.menu.main]]
      identifier = "essays"
      pre = ""
      post = ""
      name = "生活"
      url = "/categories/life/"
      title = ""
      weight = 7
    [[languages.zh-cn.menu.main]]
      identifier = "tags"
      pre = ""
      post = ""
      name = "标签"
      url = "/tags/"
      title = ""
      weight = 9
    [[languages.zh-cn.menu.main]]
      identifier = "now"
      pre = ""
      post = ""
      name = "此刻"
      url = "/now/"
      title = ""
      weight = 13
    [[languages.zh-cn.menu.main]]
      identifier = "about"
      pre = ""
      post = ""
      name = "关于"
      url = "/about/"
      title = ""
      weight = 15

  [languages.en]
    weight = 2
    languageCode = "en"
    languageName = "English"
    [languages.en.params.home.profile]
      enable = true
      # Gravatar 邮箱，用于优先在主页显示的头像
      # 主页显示头像的 URL
      avatarURL = "/avatar/myself.webp"
      # DoIt 更改 | 0.2.7 主页显示的网站标题 (支持 HTML 格式)
      title = ""
      # 主页显示的网站副标题
      subtitle = """I miss flowers, but see the sea."""
      # 是否为副标题显示打字机动画
      typeit = false
      # 是否显示社交账号
      social = true
      # DoIt 新增 | 0.2.0 免责声明 (支持 HTML 格式)
      disclaimer = ""

    [languages.en.params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 10

    [[languages.en.menu.main]]
      identifier = "series"
      pre = ""
      post = ""
      name = "Series"
      url = "/series/"
      title = ""
      weight = 3
    [[languages.en.menu.main]]
      identifier = "posts"
      pre = ""
      post = ""
      name = "Posts"
      url = "/posts/"
      title = ""
      weight = 5
    [[languages.en.menu.main]]
      identifier = "tech"
      pre = ""
      post = ""
      name = "Tech"
      url = "/categories/tech/"
      title = ""
      weight = 7
    [[languages.en.menu.main]]
      identifier = "essays"
      pre = ""
      post = ""
      name = "Life"
      url = "/categories/life/"
      title = ""
      weight = 9
    [[languages.en.menu.main]]
      identifier = "tags"
      pre = ""
      post = ""
      name = "Tags"
      url = "/tags/"
      title = ""
      weight = 11
    [[languages.en.menu.main]]
      identifier = "now"
      pre = ""
      post = ""
      name = "Now"
      url = "/now/"
      title = ""
      weight = 15
    [[languages.en.menu.main]]
      identifier = "about"
      pre = ""
      post = ""
      name = "About"
      url = "/about/"
      title = ""
      weight = 17

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false 是必要的设置
    # (https://github.com/dillonzq/DoIt/issues/158)
    noClasses = false
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  # https://gohugo.io/getting-started/configuration-markup/
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # 是否在文档中直接使用 HTML 标签
      unsafe = true
    [markup.goldmark.extensions.cjk]
      enable = true
      # 自动去除中文之间的换行（而不是将其替换为空格）
      eastAsianLineBreaks = true
      escapedSpace = true
  # 目录设置
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6


# 作者配置
[author]
  name = "alienzj"
  nickname = "alienzj"
  avatar = "https://blog.alienzj.tech/avatar/myself.webp"
  link = "https://blog.alienzj.tech/"


# 网站地图配置
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks 配置
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = "posts/:filename"

# 隐私信息配置
[privacy]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

# Atom feed
# Add "ATOM" to the Page Kinds under [outputs] (in your site config) for which
# you want to enable Atom feeds.
# Example:
#   [outputs]
#     home = ["HTML", "ATOM"]
# https://gist.github.com/lpar/7ded35d8f52fef7490a5be92e6cd6937
[mediaTypes."application/atom+xml"]
  suffixes = ["xml"]
[outputFormats.Atom]
  # https://validator.w3.org/feed/docs/atom.html#whatIsAtom
  name = "ATOM"
  mediaType = "application/atom+xml"
  baseName = "index" # generated file = <baseName>.<mediaType."application/atom+xml".suffixes[0]> = index.xml
  isPlainText = false
  rel = "alternate"
  isHTML = false
  noUgly = true
  permalinkable = false

# 用于分类的设置
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
series = "series"

# 用于 Hugo 输出文档的设置
[outputs]
  # DoIt 更改 | 0.2.0
  # 为了支持搜索，需要在这里设定，输出 json 索引文件
  # <domain>/atom.xml
  home = ["HTML", "ATOM", "JSON", "RSS"]
  page = ["HTML", "RSS"]
  section = ["HTML"]
  taxonomy = ["HTML"]
